/**
 * ReelForge — Project view: storyboard editor, asset generation, renderer,
 * captions, music, preview and MP4 export.
 *
 * Scene-level regeneration only touches that scene; re-rendering the final
 * video is a fast local operation, so editing one scene never regenerates the
 * whole project.
 */

import { el, icon, toast, confirmDlg, statusBadge, assetImg, progressBar, fmtBytes, modal } from '../ui.js';
import { getProject, putProject, saveBlob, getAsset, getAssetURL, deleteAsset } from '../../../shared/core/idb.js';
import { isConfigured } from '../../../shared/core/storage.js';
import { CAPTION_STYLES } from '../../../shared/render/captions.js';
import { MUSIC_STYLES, generateLocalMusic } from '../../../shared/render/music-synth.js';
import { STYLE_PRESETS, HOOK_CATEGORIES } from '../../../shared/ai/prompts.js';
import {
  generateProjectStoryboard, generateAllAssets, generateSceneImage, generateSceneVoice,
  generateSceneVideo, generateSceneLipSync, ensureMusic, generateCreatorPortrait,
} from '../../../shared/render/pipeline.js';
import { VideoCompositor, pickMimeType, ASPECT_DIMS } from '../../../shared/render/compositor.js';
import { uid, truncate, fmtDuration, downloadBlob, fileStamp, clamp } from '../../../shared/core/utils.js';
import { refreshSettings, state } from '../state.js';

export async function renderProject(view, id, { setTopbar }) {
  const project = await getProject(id);
  if (!project) {
    view.append(el('div', { class: 'empty' },
      el('div', { class: 'icon' }, '🗂'),
      el('h3', {}, 'Project not found'),
      el('p', {}, 'It may have been deleted.'),
      el('button', { class: 'btn primary', onclick: () => { location.hash = '#/home'; } }, 'Back to dashboard'),
    ));
    return;
  }
  state.project = project;
  const settings = state.settings;

  let genAbort = null;
  let compositor = null;
  let previewing = false;

  setTopbar(project.name || 'Project',
    el('span', { class: 'badge gray', id: 'p-status' }, project.status || 'draft'),
  );

  const save = () => putProject(project);
  const totalDur = () => (project.storyboard?.scenes || []).reduce((a, s) => a + (Number(s.durationSec) || 0), 0);

  /* --------------------------------- header -------------------------------- */

  const nameIn = el('input', { class: 'input', value: project.name || '', style: { maxWidth: '340px', fontWeight: '600' } });
  nameIn.addEventListener('change', () => { project.name = nameIn.value; save(); setTopbar(project.name); });

  const sbBtn = el('button', { class: 'btn' }, icon('wand'), project.storyboard ? 'Regenerate storyboard' : 'Generate storyboard');
  const genBtn = el('button', { class: 'btn' }, icon('spark'), 'Generate missing assets');
  const stopBtn = el('button', { class: 'btn danger', style: { display: 'none' } }, icon('x'), 'Stop');
  const previewBtn = el('button', { class: 'btn' }, icon('play'), 'Preview');
  const renderBtn = el('button', { class: 'btn primary' }, icon('film'), 'Render video');
  const creatorBtn = project.input.personAutoGenerated ? el('button', { class: 'btn small' }, '↻ New AI creator') : null;

  view.append(el('div', { class: 'page-head' },
    el('div', {},
      nameIn,
      el('div', { class: 'row', style: { marginTop: '8px', gap: '8px' } },
        el('span', { class: 'badge violet' }, project.input.aspect),
        el('span', { class: 'badge cyan' }, `${STYLE_PRESETS.find((s) => s.id === project.input.stylePreset)?.name || 'Custom'}`),
        el('span', { class: 'badge gray' }, `${project.storyboard?.scenes?.length || 0} scenes · ${fmtDuration(totalDur())}`),
        project.input.beautyMode ? el('span', { class: 'badge pink' }, 'Beauty mode') : null,
      ),
    ),
    el('div', { class: 'actions' },
      creatorBtn, sbBtn, genBtn, stopBtn, previewBtn, renderBtn,
    ),
  ));

  /* ------------------------------ setup banner ----------------------------- */

  const missingProviders = [];
  if (!isConfigured('llm', settings)) missingProviders.push(['llm', 'LLM — script understanding & storyboard']);
  if (!isConfigured('image', settings)) missingProviders.push(['image', 'Image AI — scene visuals']);
  if (!isConfigured('tts', settings)) missingProviders.push(['tts', 'Voice AI — creator voice-over']);
  if (project.options?.talkingCreator && !isConfigured('lipsync', settings)) missingProviders.push(['lipsync', 'Lip-sync AI — talking creator']);
  if (project.options?.animateScenes && !isConfigured('video', settings)) missingProviders.push(['video', 'Video AI — animated clips']);
  if (missingProviders.length) {
    const note = el('div', { class: 'note warn', style: { marginBottom: '18px' } },
      el('b', {}, 'Providers that would improve this video: '), el('br'),
      ...missingProviders.map(([, label]) => `• ${label}${el('br').textContent ? '' : ''}`),
      ' ',
      el('a', { href: '#/settings' }, 'Open Settings →'),
    );
    view.append(note);
  }

  /* --------------------------------- stage --------------------------------- */

  const aspect = project.input.aspect || '9:16';
  const stageClass = aspect === '1:1' ? 'ratio-1-1' : aspect === '16:9' ? 'ratio-16-9' : '';
  const canvas = el('canvas');
  const stage = el('div', { class: `stage ${stageClass}` },
    canvas,
    el('div', { class: 'overlay-msg', id: 'stage-msg' }, 'Preview & rendered video appear here'),
  );

  const genProgress = progressBar('Idle');
  const timeLbl = el('div', { class: 'hint' }, ' ');
  const resultBox = el('div', {});

  const stagePanel = el('div', { class: 'card', style: { flex: '1 1 380px', minWidth: '320px' } },
    el('h3', {}, 'Preview & export'),
    el('p', { class: 'sub' }, 'Rendering happens locally in your browser — the AI assets (images, voice, clips) come from your connected providers.'),
    stage,
    el('div', { style: { marginTop: '12px' } }, genProgress.root, timeLbl),
    el('div', { class: 'row', style: { marginTop: '12px' } },
      previewBtn,
      renderBtn,
    ),
    resultBox,
  );

  const rightPanel = el('div', { style: { flex: '1 1 460px', minWidth: '320px', display: 'flex', flexDirection: 'column', gap: '16px' } },
    musicCard(), captionsCard(), scenesHelpCard(),
  );

  view.append(el('div', { class: 'stage-wrap' }, stagePanel, rightPanel));

  /* ------------------------------- storyboard ------------------------------ */

  const sbHead = el('div', { class: 'row', style: { margin: '26px 0 12px' } },
    el('h3', { style: { margin: 0, fontSize: '17px', flex: 1 } }, 'Storyboard'),
    el('button', { class: 'btn small', id: 'add-scene' }, icon('plus'), 'Add scene'),
  );
  const sceneGrid = el('div', { class: 'scene-grid' });
  const timeline = el('div', { class: 'timeline', style: { marginTop: '16px' } });
  const sbSection = el('div', {}, sbHead, sceneGrid, timeline);
  view.append(sbSection);

  /* -------------------------------- actions -------------------------------- */

  sbBtn.addEventListener('click', async () => {
    if (project.storyboard && !(await confirmDlg({
      title: 'Regenerate storyboard?',
      body: 'The current scenes and their edits will be replaced (generated media stays until scenes are replaced).',
      okLabel: 'Regenerate',
    }))) return;
    if (!isConfigured('llm', settings)) { toast('Configure an LLM provider first (Settings → Providers).', 'error', 6000); return; }
    sbBtn.disabled = true;
    genProgress.set(0.2, 'The AI director is writing the storyboard…');
    try {
      await generateProjectStoryboard(project);
      toast('Storyboard updated', 'success');
      paintScenes();
    } catch (e) {
      toast(`Storyboard failed: ${truncate(e.message, 200)}`, 'error', 8000);
    }
    genProgress.set(0, 'Idle');
    sbBtn.disabled = false;
  });

  genBtn.addEventListener('click', async () => {
    if (!project.storyboard?.scenes?.length) { toast('Generate the storyboard first.', 'warn'); return; }
    genAbort = new AbortController();
    genBtn.disabled = true; renderBtn.disabled = true; previewBtn.disabled = true;
    stopBtn.style.display = '';
    try {
      const res = await generateAllAssets(project, {
        signal: genAbort.signal,
        includeVideo: project.options?.animateScenes && isConfigured('video', settings),
        includeLipSync: project.options?.talkingCreator && isConfigured('lipsync', settings),
        onProgress: ({ label, done, total, error }) => {
          genProgress.set(total ? done / total : 0, label);
        },
      });
      if (res.failures.length) {
        toast(`${res.done}/${res.total} steps completed · ${res.failures.length} failed — press "Generate missing assets" again to retry only the failed ones.`, 'warn', 9000);
        console.warn('[ReelForge] failures:', res.failures);
      } else {
        toast('All assets generated ✓ Ready to render.', 'success', 6000);
      }
      paintScenes();
    } catch (e) {
      if (e.name !== 'AbortError') toast(truncate(e.message, 300), 'error', 8000);
    }
    genProgress.set(0, 'Idle');
    genBtn.disabled = false; renderBtn.disabled = false; previewBtn.disabled = false;
    stopBtn.style.display = 'none';
  });

  stopBtn.addEventListener('click', () => { genAbort?.abort(); toast('Stopping after the current step…', 'info'); });

  creatorBtn?.addEventListener('click', async () => {
    try {
      creatorBtn.disabled = true;
      genProgress.set(0.3, 'Designing a new AI creator…');
      await generateCreatorPortrait(project, { force: true });
      genProgress.set(0, 'Idle');
      toast('New AI creator generated — regenerate scene images to apply her look.', 'success', 7000);
    } catch (e) {
      genProgress.set(0, 'Idle');
      toast(truncate(e.message, 250), 'error', 7000);
    }
    creatorBtn.disabled = false;
  });

  previewBtn.addEventListener('click', async () => {
    if (previewing) { compositor?.stop(); return; }
    if (!project.storyboard?.scenes?.length) { toast('Nothing to preview yet.', 'warn'); return; }
    previewing = true;
    previewBtn.innerHTML = `${icon('stop').innerHTML} Stop preview`;
    stage.querySelector('#stage-msg')?.remove();
    try {
      await ensureMusic(project);
      compositor = new VideoCompositor({
        canvas, project, settings,
        onTime: (t, total) => { timeLbl.textContent = `Preview ${fmtDuration(t)} / ${fmtDuration(total)}`; },
        onProgress: (p) => genProgress.set(p, 'Previewing…'),
      });
      await compositor.prepare();
      await compositor.play();
    } catch (e) {
      if (e.message !== 'Rendering cancelled.') toast(`Preview: ${e.message}`, 'error', 7000);
    }
    compositor?.destroy(); compositor = null;
    previewing = false;
    genProgress.set(0, 'Idle'); timeLbl.textContent = ' ';
    previewBtn.innerHTML = `${icon('play').innerHTML} Preview`;
  });

  renderBtn.addEventListener('click', async () => {
    if (!project.storyboard?.scenes?.length) { toast('Generate the storyboard first.', 'warn'); return; }
    renderBtn.disabled = true; previewBtn.disabled = true;
    stage.querySelector('#stage-msg')?.remove();
    resultBox.innerHTML = '';
    try {
      genProgress.set(0.02, 'Preparing music…');
      await ensureMusic(project);
      genProgress.set(0.05, 'Loading assets…');
      const comp = new VideoCompositor({ canvas, project, settings, silent: true });
      await comp.prepare();
      const mime = pickMimeType();
      genProgress.set(0.08, `Rendering ${mime.includes('mp4') ? 'MP4' : 'WebM'} in real time — ${fmtDuration(comp.total)}…`);
      const result = await comp.record();
      comp.destroy();

      const asset = await saveBlob(result.blob, { type: result.mime, name: 'final-video' });
      project.render = {
        videoAssetId: asset.id, mime: result.mime, ext: result.ext,
        durationSec: Math.round(result.durationSec), size: result.blob.size, renderedAt: Date.now(),
      };
      project.status = 'rendered';
      await save();
      genProgress.set(1, 'Render complete ✓');
      showResult();
      toast(`Video rendered (${result.ext.toUpperCase()}, ${fmtBytes(result.blob.size)})`, 'success', 6000);
    } catch (e) {
      genProgress.set(0, 'Render failed');
      toast(`Render failed: ${truncate(e.message, 250)}`, 'error', 9000);
    }
    renderBtn.disabled = false; previewBtn.disabled = false;
  });

  function showResult() {
    resultBox.innerHTML = '';
    if (!project.render?.videoAssetId) return;
    const urlPromise = getAssetURL(project.render.videoAssetId);
    const video = el('video', { class: 'result-video', controls: true, style: { marginTop: '14px', maxHeight: '420px' } });
    urlPromise.then((u) => { if (u) video.src = u; });
    resultBox.append(
      el('hr', { class: 'divider' }),
      el('div', { class: 'row', style: { gap: '8px' } },
        el('span', { class: 'badge green' }, 'Rendered'),
        el('span', { class: 'hint' }, `${project.render.ext.toUpperCase()} · ${project.render.durationSec}s · ${fmtBytes(project.render.size)} · ${new Date(project.render.renderedAt).toLocaleTimeString()}`),
      ),
      video,
      el('div', { class: 'row', style: { marginTop: '12px' } },
        el('button', {
          class: 'btn primary',
          onclick: async () => {
            const rec = await getAsset(project.render.videoAssetId);
            if (!rec) { toast('Rendered file missing — re-render.', 'error'); return; }
            const safe = (project.name || 'reelforge').replace(/[^a-z0-9-_ ]/gi, '').trim().replace(/\s+/g, '-');
            const filename = `${safe || 'reelforge'}-${fileStamp()}.${project.render.ext}`;
            // Prefer the chrome.downloads API (streams large files to disk),
            // with a plain anchor fallback when unavailable.
            if (typeof chrome !== 'undefined' && chrome.downloads?.download) {
              const url = URL.createObjectURL(rec.blob);
              try {
                await chrome.downloads.download({ url, filename, saveAs: true });
                setTimeout(() => URL.revokeObjectURL(url), 120000);
                return;
              } catch { URL.revokeObjectURL(url); }
            }
            downloadBlob(rec.blob, filename);
          },
        }, icon('download'), 'Download video'),
        el('button', { class: 'btn', onclick: () => renderBtn.click() }, icon('refresh'), 'Re-render'),
      ),
    );
  }

  /* ------------------------------ music card ------------------------------- */

  function musicCard() {
    const card = el('div', { class: 'card' });
    const paint = () => {
      card.innerHTML = '';
      const m = project.music || {};
      card.append(
        el('h3', {}, '🎵 Background music'),
        el('p', { class: 'sub' }, 'Auto-ducked under the voice. Local generator = royalty-free-style procedural track (offline). Only use uploaded tracks you have the license to.'),
      );
      const source = el('select', { class: 'input' },
        el('option', { value: 'local', selected: (m.source || 'local') === 'local' }, 'Local procedural generator (free)'),
        ...(isConfigured('music', settings) && settings.music.provider !== 'local'
          ? [el('option', { value: 'provider', selected: m.source === 'provider' }, `${settings.music.provider} AI music`)] : []),
        el('option', { value: 'upload', selected: m.source === 'upload' }, 'Uploaded track'),
      );
      const style = el('select', { class: 'input', style: { marginTop: '8px', display: m.source === 'provider' ? 'none' : '' } },
        ...MUSIC_STYLES.map((s) => el('option', { value: s.id, selected: (m.styleId || 'upbeat-pop') === s.id }, `${s.label} — ${s.hint}`)));
      style.addEventListener('change', () => { project.music = { ...m, styleId: style.value }; save(); });

      const regen = el('button', { class: 'btn small', style: { marginTop: '10px' } }, icon('refresh'), m.assetId ? 'Regenerate music' : 'Generate music');
      regen.addEventListener('click', async () => {
        regen.disabled = true;
        genProgress.set(0.3, 'Composing music…');
        try {
          await ensureMusic(project, { forceRegenerate: true });
          genProgress.set(0, 'Idle');
          toast('Music ready', 'success');
          paint(); paintScenes();
        } catch (e) {
          genProgress.set(0, 'Idle');
          toast(`Music: ${truncate(e.message, 220)}`, 'error', 7000);
        }
        regen.disabled = false;
      });

      const uploadWrap = el('div', { style: { marginTop: '10px', display: m.source === 'upload' ? '' : 'none' } });
      import('../ui.js').then(({ dropzone }) => {
        uploadWrap.append(dropzone({
          accept: 'audio/*', label: 'Upload music file', sub: 'MP3 · WAV · M4A',
          onFiles: async ([f]) => {
            const asset = await saveBlob(f, { name: f.name, type: f.type });
            project.music = { ...m, source: 'upload', uploadedAssetId: asset.id };
            await save();
            toast('Music uploaded', 'success');
            paint();
          },
        }));
      });

      source.addEventListener('change', () => {
        project.music = { ...m, source: source.value };
        save();
        paint();
      });

      const vol = el('input', { type: 'range', min: '0', max: '1', step: '0.02', value: settings.defaults.musicVolume });
      const volLbl = el('span', { class: 'hint', style: { minWidth: '36px' } }, `${Math.round(settings.defaults.musicVolume * 100)}%`);
      vol.addEventListener('input', async () => {
        volLbl.textContent = `${Math.round(vol.value * 100)}%`;
        settings.defaults.musicVolume = Number(vol.value);
        await refreshSettings.save?.();
        const { saveSettings } = await import('../../../shared/core/storage.js');
        await saveSettings(settings);
      });

      if (m.assetId) {
        const player = el('audio', { controls: true, style: { width: '100%', marginTop: '10px' } });
        getAssetURL(m.assetId).then((u) => { if (u) player.src = u; });
        card.append(player);
      }

      card.append(
        el('label', { class: 'field', style: { marginTop: '10px' } }, el('span', {}, 'Music source'), source),
        style,
        uploadWrap,
        regen,
        el('label', { class: 'field', style: { marginTop: '12px' } },
          el('span', {}, 'Music volume'), el('div', { style: { display: 'flex', gap: '10px', alignItems: 'center' } }, vol, volLbl)),
      );
    };
    paint();
    return card;
  }

  /* ----------------------------- captions card ----------------------------- */

  function captionsCard() {
    const c = project.captions || {};
    const card = el('div', { class: 'card' });
    const paint = () => {
      card.innerHTML = '';
      card.append(el('h3', {}, '💬 Captions'), el('p', { class: 'sub' }, 'Word-level animated captions are rendered locally. Timing is derived from the generated voice duration.'));

      const style = el('select', { class: 'input' },
        ...CAPTION_STYLES.map((s) => el('option', { value: s.id, selected: (c.style || settings.defaults.captionStyle) === s.id }, `${s.label} — ${s.hint}`)));
      style.addEventListener('change', () => { project.captions = { ...c, style: style.value }; save(); paint(); });

      const size = el('input', { type: 'range', min: '34', max: '84', step: '2', value: c.fontSize || 54 });
      const sizeLbl = el('span', { class: 'hint', style: { minWidth: '30px' } }, String(c.fontSize || 54));
      size.addEventListener('input', () => { sizeLbl.textContent = size.value; project.captions = { ...c, fontSize: Number(size.value) }; save(); });

      const pos = el('input', { type: 'range', min: '0.5', max: '0.92', step: '0.01', value: c.positionY || 0.78 });
      pos.addEventListener('input', () => { project.captions = { ...c, positionY: Number(pos.value) }; save(); });

      const color = el('input', { type: 'color', class: 'input', value: c.color || '#ffffff' });
      color.addEventListener('input', () => { project.captions = { ...c, color: color.value }; save(); });
      const hcolor = el('input', { type: 'color', class: 'input', value: c.highlightColor || '#facc15' });
      hcolor.addEventListener('input', () => { project.captions = { ...c, highlightColor: hcolor.value }; save(); });

      const anim = el('select', { class: 'input' },
        ...['pop', 'slide', 'fade', 'none'].map((a) => el('option', { value: a, selected: (c.animation || 'pop') === a }, a)));

      card.append(
        el('label', { class: 'field' }, el('span', {}, 'Caption style'), style),
        el('label', { class: 'field' }, el('span', {}, 'Font size'), el('div', { style: { display: 'flex', gap: '10px', alignItems: 'center' } }, size, sizeLbl)),
        el('label', { class: 'field' }, el('span', {}, 'Vertical position'), pos),
        el('div', { class: 'grid cols-2' },
          el('label', { class: 'field' }, el('span', {}, 'Text color'), color),
          el('label', { class: 'field' }, el('span', {}, 'Highlight color'), hcolor),
        ),
        el('label', { class: 'field' }, el('span', {}, 'Word animation'), anim),
      );
    };
    paint();
    return card;
  }

  function scenesHelpCard() {
    return el('div', { class: 'card' },
      el('h3', {}, '🧠 How generation works'),
      el('p', { class: 'sub', style: { marginBottom: '8px' } }, 'Each scene generates independently:'),
      el('div', { style: { fontSize: '12.5px', color: 'var(--muted)', lineHeight: '1.8' } },
        '1. ', el('b', {}, 'Voice'), ' — TTS reads the dialog; scene duration adapts to the audio length.', el('br'),
        '2. ', el('b', {}, 'Image'), ' — image AI renders the scene using the creator + product photos as identity references.', el('br'),
        '3. ', el('b', {}, 'Video clip'), ' (optional) — image-to-video AI animates the still.', el('br'),
        '4. ', el('b', {}, 'Lip-sync'), ' (optional) — the creator image is animated with her voice.', el('br'),
        '5. ', el('b', {}, 'Render'), ' — local compositor adds camera moves, transitions, captions, music, CTA card and exports MP4.'),
      el('p', { class: 'hint', style: { marginTop: '10px' } }, 'Editing one scene never regenerates the others. Re-rendering the final video is a fast local operation.'),
    );
  }

  /* ------------------------------- scene board ------------------------------ */

  function paintScenes() {
    sceneGrid.innerHTML = '';
    timeline.innerHTML = '';
    const scenes = project.storyboard?.scenes || [];
    document.getElementById('add-scene').style.display = scenes.length ? '' : 'none';

    if (!scenes.length) {
      sceneGrid.append(el('div', { class: 'empty', style: { gridColumn: '1/-1' } },
        el('div', { class: 'icon' }, '📝'),
        el('h3', {}, 'No storyboard yet'),
        el('p', {}, 'Click "Generate storyboard" and the AI director will convert your script into scenes with dialog, camera directions, captions and timing.'),
      ));
      return;
    }

    scenes.forEach((scene, i) => {
      scene.index = i;
      const thumb = el('div', { class: 'thumb' },
        el('span', { class: 'idx' }, `#${i + 1}`),
        el('span', { class: 'role badge violet' }, scene.role),
        scene.assets?.imageAssetId ? assetImg(scene.assets.imageAssetId) : el('div', { style: { color: 'var(--faint)', fontSize: '11px', textAlign: 'center', padding: '8px' } }, 'no image yet'),
        el('span', { class: 'status' }, statusDot(scene.status), sceneLabel(scene.status)),
      );
      const card = el('div', { class: 'scene-card', draggable: 'true', dataset: { sceneId: scene.id } },
        thumb,
        el('div', { class: 'qactions' },
          el('button', { class: 'btn small icon', title: 'Regenerate image', onclick: (e) => { e.stopPropagation(); regenImage(scene); } }, icon('refresh')),
          el('button', { class: 'btn small icon', title: 'Duplicate', onclick: (e) => { e.stopPropagation(); duplicateScene(scene); } }, icon('dup')),
          el('button', { class: 'btn small icon', title: 'Delete', onclick: (e) => { e.stopPropagation(); removeScene(scene); } }, icon('trash')),
        ),
        el('div', { class: 'body' },
          el('div', { class: 'dialog' }, scene.dialog || el('i', { style: { color: 'var(--faint)' } }, 'no dialog')),
          scene.onScreenText ? el('div', { style: { fontSize: '10.5px', color: 'var(--accent-3)' } }, `“${scene.onScreenText}”`) : null,
        ),
        el('div', { class: 'foot' },
          el('span', {}, `${Number(scene.durationSec).toFixed(1)}s`),
          el('span', {}, `· ${scene.cameraMove}`),
          scene.assets?.audioAssetId ? el('span', { title: 'voice ready' }, '· 🔊') : null,
          scene.assets?.lipsyncAssetId ? el('span', { title: 'lip-sync ready' }, '· 👄') : null,
          scene.assets?.videoAssetId ? el('span', { title: 'AI video clip ready' }, '· 🎞') : null,
        ),
      );
      card.addEventListener('click', () => openSceneEditor(scene));
      card.addEventListener('dragstart', (e) => { e.dataTransfer.setData('text/plain', String(i)); card.classList.add('dragging'); });
      card.addEventListener('dragend', () => card.classList.remove('dragging'));
      card.addEventListener('dragover', (e) => e.preventDefault());
      card.addEventListener('drop', (e) => {
        e.preventDefault();
        const from = Number(e.dataTransfer.getData('text/plain'));
        if (!Number.isInteger(from) || from === i) return;
        reorder(from, i);
      });
      sceneGrid.append(card);
    });

    // timeline strip
    const colors = { hook: '#8b5cf6', problem: '#f87171', experience: '#fbbf24', 'product-intro': '#34d399', demo: '#22d3ee', benefits: '#60a5fa', result: '#a78bfa', 'social-proof': '#f472b6', cta: '#ec4899', other: '#64748b' };
    scenes.forEach((s, i) => {
      const seg = el('div', {
        class: `tl-seg ${s.status === 'error' ? 'error' : ''}`,
        style: { flexGrow: String(Number(s.durationSec) || 1), background: `linear-gradient(135deg, ${colors[s.role] || colors.other}66, ${colors[s.role] || colors.other}33)` },
        title: `${s.role}: ${truncate(s.dialog, 80)}`,
      }, el('b', {}, `#${i + 1} ${s.role}`), el('small', {}, truncate(s.dialog || s.description, 30)), el('span', { class: 'dur' }, `${Number(s.durationSec).toFixed(1)}s`));
      seg.addEventListener('click', () => openSceneEditor(s));
      timeline.append(seg);
    });
    const ctaSeg = el('div', { class: 'tl-seg', style: { flexGrow: '2.6', background: 'linear-gradient(135deg, #ec489966, #8b5cf633)' } },
      el('b', {}, 'CTA card'), el('small', {}, project.brand?.cta || 'brand end-card'), el('span', { class: 'dur' }, '2.6s'));
    timeline.append(ctaSeg);
  }

  function statusDot(status) {
    const map = { ready: 'ok', error: 'err', generating: 'busy', pending: 'pending' };
    return el('span', { class: `dot ${map[status] || 'pending'}` });
  }
  function sceneLabel(status) {
    return { ready: 'ready', error: 'failed', generating: 'working…', pending: 'pending' }[status] || status;
  }

  async function regenImage(scene) {
    if (!isConfigured('image', settings)) { toast('Configure an image provider first (Settings).', 'error', 5000); return; }
    scene.status = 'generating'; paintScenes();
    try {
      await generateSceneImage(project, scene, { force: true });
      toast(`Scene ${scene.index + 1} image regenerated`, 'success');
    } catch (e) {
      toast(`Scene ${scene.index + 1}: ${truncate(e.message, 200)}`, 'error', 7000);
    }
    paintScenes();
  }

  async function duplicateScene(scene) {
    const copy = JSON.parse(JSON.stringify(scene));
    copy.id = uid('scn');
    copy.assets = { imageAssetId: null, videoAssetId: null, audioAssetId: null, lipsyncAssetId: null };
    copy.status = 'pending';
    const scenes = project.storyboard.scenes;
    scenes.splice(scene.index + 1, 0, copy);
    scenes.forEach((s, i) => { s.index = i; });
    await save();
    paintScenes();
    toast('Scene duplicated (media not copied — regenerate what you need)', 'info', 5000);
  }

  async function removeScene(scene) {
    if (!(await confirmDlg({ title: `Delete scene ${scene.index + 1}?`, body: truncate(scene.dialog, 100), okLabel: 'Delete', danger: true }))) return;
    project.storyboard.scenes.splice(scene.index, 1);
    project.storyboard.scenes.forEach((s, i) => { s.index = i; });
    await save();
    paintScenes();
  }

  async function reorder(from, to) {
    const scenes = project.storyboard.scenes;
    const [moved] = scenes.splice(from, 1);
    scenes.splice(to, 0, moved);
    scenes.forEach((s, i) => { s.index = i; });
    await save();
    paintScenes();
  }

  document.getElementById('add-scene').addEventListener('click', () => {
    const scenes = project.storyboard?.scenes || [];
    if (!project.storyboard) project.storyboard = { title: project.name, scenes: [] };
    const scene = {
      id: uid('scn'), index: scenes.length, role: 'other', description: '', dialog: '',
      expression: '', gesture: '', camera: '', cameraMove: 'push-in', background: '', lighting: '',
      productPlacement: '', productInteraction: '', onScreenText: '', caption: '', durationSec: 3.5,
      transition: 'crossfade', focus: 'person',
      assets: { imageAssetId: null, videoAssetId: null, audioAssetId: null, lipsyncAssetId: null },
      gen: { imagePrompt: null, videoPrompt: null, imageModel: null },
      productImageRef: null, status: 'pending', error: null,
    };
    project.storyboard.scenes.push(scene);
    save().then(() => { paintScenes(); openSceneEditor(scene); });
  });

  /* ----------------------------- scene editor ------------------------------ */

  function openSceneEditor(scene) {
    const content = el('div', {});
    const fields = {};
    const F = (key, label, type = 'text', rows) => {
      let input;
      if (type === 'textarea') {
        input = el('textarea', { class: 'input', rows: rows || '2' });
      } else if (type === 'select') {
        input = el('select', { class: 'input' });
      } else if (type === 'number') {
        input = el('input', { class: 'input', type: 'number', step: '0.1', min: '1', max: '12' });
      } else {
        input = el('input', { class: 'input' });
      }
      input.value = scene[key] ?? '';
      input.addEventListener('input', () => {
        scene[key] = type === 'number' ? Number(input.value) : input.value;
        save();
      });
      fields[key] = input;
      return el('label', { class: 'field' }, el('span', {}, label), input);
    };

    const roles = ['hook', 'problem', 'experience', 'product-intro', 'demo', 'benefits', 'result', 'social-proof', 'cta', 'other'];
    fields.role = el('select', { class: 'input' }, ...roles.map((r) => el('option', { value: r, selected: scene.role === r }, r)));
    fields.role.addEventListener('change', () => { scene.role = fields.role.value; save(); paintScenes(); });

    const moves = ['static', 'push-in', 'pull-out', 'pan-left', 'pan-right', 'tilt-up', 'handheld', 'orbit'];
    fields.cameraMove = el('select', { class: 'input' }, ...moves.map((m) => el('option', { value: m, selected: scene.cameraMove === m }, m)));
    fields.cameraMove.addEventListener('change', () => { scene.cameraMove = fields.cameraMove.value; save(); });

    const trans = ['cut', 'crossfade', 'whip', 'slide', 'fade-black'];
    fields.transition = el('select', { class: 'input' }, ...trans.map((m) => el('option', { value: m, selected: scene.transition === m }, m)));
    fields.transition.addEventListener('change', () => { scene.transition = fields.transition.value; save(); });

    const focuses = ['person', 'product', 'both'];
    fields.focus = el('select', { class: 'input' }, ...focuses.map((m) => el('option', { value: m, selected: scene.focus === m }, m)));
    fields.focus.addEventListener('change', () => { scene.focus = fields.focus.value; save(); });

    // assets preview
    const assetsBox = el('div', { class: 'grid cols-2', style: { marginBottom: '12px' } });
    const paintAssets = () => {
      assetsBox.innerHTML = '';
      const A = (label, assetId, kind) => {
        const box = el('div', { class: 'card', style: { padding: '10px' } },
          el('div', { class: 'hint', style: { marginBottom: '6px', display: 'flex', justifyContent: 'space-between' } },
            el('b', {}, label), assetId ? el('span', { class: 'badge green' }, 'ready') : el('span', { class: 'badge gray' }, 'none')),
        );
        if (assetId) {
          if (kind === 'image') box.append(assetImg(assetId, label));
          else if (kind === 'video') {
            const v = el('video', { controls: true, style: { width: '100%', borderRadius: '8px' } });
            getAssetURL(assetId).then((u) => { if (u) v.src = u; });
            box.append(v);
          } else if (kind === 'audio') {
            const a = el('audio', { controls: true, style: { width: '100%' } });
            getAssetURL(assetId).then((u) => { if (u) a.src = u; });
            box.append(a);
          }
        }
        return box;
      };
      assetsBox.append(
        A('Scene image', scene.assets.imageAssetId, 'image'),
        A('Voice-over', scene.assets.audioAssetId, 'audio'),
        A('AI video clip', scene.assets.videoAssetId, 'video'),
        A('Lip-synced talking clip', scene.assets.lipsyncAssetId, 'video'),
      );
    };
    paintAssets();

    // product image selection
    const prodBox = el('div', { class: 'thumb-strip', style: { marginTop: '6px' } });
    const paintProd = () => {
      prodBox.innerHTML = '';
      (project.input.images || []).forEach((imgId, i) => {
        const t = el('div', {
          class: 'thumb', style: { width: '64px', height: '84px', cursor: 'pointer', outline: scene.productImageRef === imgId ? '2.5px solid var(--accent)' : 'none' },
          title: `Use PRODUCT-${i + 1} in this scene`,
        }, assetImg(imgId), el('span', { class: 'tag' }, `P${i + 1}`));
        t.addEventListener('click', () => {
          scene.productImageRef = scene.productImageRef === imgId ? null : imgId;
          save(); paintProd();
        });
        prodBox.append(t);
      });
      if (!(project.input.images || []).length) prodBox.append(el('span', { class: 'hint' }, 'No product photos uploaded.'));
    };
    paintProd();

    // regeneration buttons
    const genRow = el('div', { class: 'row', style: { marginTop: '6px' } });
    const mkGen = (label, fn) => {
      const b = el('button', { class: 'btn small' }, icon('refresh'), label);
      b.addEventListener('click', async () => {
        b.disabled = true; b.innerHTML = '<span class="spinner"></span> working…';
        try { await fn(); paintAssets(); paintScenes(); toast(`Scene ${scene.index + 1}: ${label.toLowerCase()} done`, 'success', 3000); }
        catch (e) { toast(truncate(e.message, 260), 'error', 8000); }
        b.disabled = false; b.innerHTML = `${icon('refresh').innerHTML} ${label}`;
      });
      return b;
    };
    genRow.append(
      mkGen('Voice', () => generateSceneVoice(project, scene, { force: true })),
      mkGen('Image', () => generateSceneImage(project, scene, { force: true })),
      mkGen('Video clip', () => generateSceneVideo(project, scene, { force: true })),
      mkGen('Lip-sync', () => generateSceneLipSync(project, scene, { force: true })),
    );

    const promptArea = el('textarea', { class: 'input', rows: '4', placeholder: 'Image prompt (auto-built from the scene — edit to override)' });
    promptArea.value = scene.gen?.imagePrompt || '';
    promptArea.addEventListener('input', () => {
      scene.gen = { ...(scene.gen || {}), imagePrompt: promptArea.value || null };
      save();
    });

    content.append(
      el('div', { class: 'row' },
        el('label', { class: 'field grow' }, el('span', {}, 'Scene role'), fields.role),
        el('label', { class: 'field' }, el('span', {}, 'Focus'), fields.focus),
        el('label', { class: 'field' }, el('span', {}, 'Duration (s)'), fields.durationSec = numField('durationSec', scene.durationSec)),
        el('label', { class: 'field' }, el('span', {}, 'Transition in'), fields.transition),
      ),
      el('div', { class: 'row' },
        fieldWrap('Camera shot', F('camera', ''), 'grow'),
        el('label', { class: 'field' }, el('span', {}, 'Camera move'), fields.cameraMove),
      ),
      F('description', 'What we see (director description)', 'textarea', 2),
      F('dialog', 'What the creator says (spoken)', 'textarea', 3),
      el('div', { class: 'grid cols-2' },
        F('expression', 'Facial expression'),
        F('gesture', 'Hand / body gesture'),
      ),
      el('div', { class: 'grid cols-2' },
        F('background', 'Background'),
        F('lighting', 'Lighting'),
      ),
      el('div', { class: 'grid cols-2' },
        F('productPlacement', 'Product placement'),
        F('productInteraction', 'Product interaction'),
      ),
      el('div', { class: 'grid cols-2' },
        F('onScreenText', 'On-screen text overlay'),
        F('caption', 'Caption (subtitles)'),
      ),
      el('div', { class: 'hint', style: { margin: '4px 0 6px' } }, 'Product photo used in this scene:'),
      prodBox,
      el('hr', { class: 'divider' }),
      el('h3', { style: { fontSize: '14px', margin: '0 0 10px' } }, 'Generated assets'),
      assetsBox,
      genRow,
      el('details', { style: { marginTop: '12px' } },
        el('summary', { style: { cursor: 'pointer', color: 'var(--muted)', fontSize: '12.5px' } }, 'Advanced: image prompt'),
        el('div', { style: { marginTop: '8px' } }, promptArea),
      ),
      scene.error ? el('div', { class: 'note danger', style: { marginTop: '10px' } }, `Last error: ${scene.error}`) : null,
    );

    modal({
      title: `Scene ${scene.index + 1} — ${scene.role}`,
      content,
      wide: true,
    });
  }

  function numField(key, value) {
    const input = el('input', { class: 'input', type: 'number', step: '0.1', min: '1', max: '12', value: String(value ?? 3.5) });
    input.addEventListener('change', () => {
      const s = project.storyboard.scenes.find((x) => x.id === scene.id);
      if (s) { s.durationSec = clamp(Number(input.value) || 3.5, 1, 12); save(); paintScenes(); }
    });
    return input;
  }

  function fieldWrap(label, inputEl, cls = '') {
    return el('label', { class: `field ${cls}` }, el('span', {}, label), inputEl);
  }

  /* --------------------------------- cleanup -------------------------------- */

  paintScenes();
  showResult();

  return () => {
    compositor?.destroy();
    genAbort?.abort();
  };
}
